### ISSUE TITLE
matsim.runtime.eqasim - Unable to delete output file 

### ISSUE THREAD

**Issue by subrina0013** [eqasim-org/eqasim-java#114]
1st, thanks for your awesome repositories. I am not sure if you have any specific place to post questions. I am trying to run your California pipeline with my own data. However, when running 'matsim.simulation.prepare' it downloads eqasim-java correctly but fails while running test. I guess may be it is trying to delete the output png file before it was closed during test run. Can you please help me?

> Error injecting constructor, org.matsim.core.utils.io.UncheckedIOException: java.nio.file.FileSystemException: simulation_output\ITERS\it.2\2.drt_detours_drt_rideTimePlot.png: The process cannot access the file because it is being used by another process

Thanks

**Comment by sebhoerl** [comment]
Maybe try to manually clean the cache directory (i.e. delete it)

**Comment by sebhoerl** [comment]
Usually, this problem occurs if you have the file still opened (for instance, in this case, if you have the image open in another window to look at it). Another instance where we have seen this is when the pipeline is run in a OneDrive folder that is synchronized (which is not advised as there are many file synchs in parallel).
