### ISSUE TITLE
Swiss config does not include separate replanning strategies for freight agents

### ISSUE THREAD

**Issue by ctchervenkov** [eqasim-org/eqasim-java#147]
The scenario for Switzerland contains a separate `freight` population, which should have a different replanning strategy from the normal population. However, this subpopulation-specific replanning strategy is not defined in the base config, and not adapted in the Swiss `ConfigAdapter`, causing the `RunSimulation` class to fail if the config file is not manually edited.

As a first simple fix, the `ConfigAdapter` should be extended to add the necessary changes.

**Comment by sebhoerl** [comment]
@balacmi Is this still relevant?

**Comment by balacmi** [comment]
Not sure why freight should have a different strategy? They are rerouted in any case through the DMC, no?

**Comment by sebhoerl** [comment]
I woudln't know, I cannot run Swiss scenarios ;)

**Comment by sebhoerl** [comment]
Yes, but according to Tchervi's comment something "fails"

**Comment by balacmi** [comment]
I don't think this applies anymore and can be closed as far as I am concerned
