### ISSUE TITLE
adding spatial attributes to activity in the population file , 

### ISSUE THREAD

**Issue by gharaviSara** [eqasim-org/eqasim-java#162]
Dear All,
I am trying to add my estimated spatial variable for each origin and destination coordinates of activity , I tried to customize matsim.writer and matsim population to add this urban variable , 

here is the final structure , 
![image](https://github.com/eqasim-org/eqasim-java/assets/61546453/b06dc246-6916-47c7-8868-131e4734d6cd)

 I also attached the writer and population codes ,
 but while I run simulation in eqasim I got this error 
 
 org.xml.sax.SAXParseException; lineNumber: 66; columnNumber: 12; The content of element type "plan" must match "(attributes?,(activity|leg)*)".

could you guide me with this issue 
[population.zip](https://github.com/eqasim-org/eqasim-java/files/11548898/population.zip)

**Comment by sebhoerl** [comment]
The XML format is not correct, you close the leg element (`<leg ... />`), but the attributes should be wrapped in it.

**Comment by gharaviSara** [comment]
thanks sebastian , I correct it by few lines of java , matsim api code 


package org.eqasim.quebec;


import org.matsim.api.core.v01.Id;

import org.matsim.api.core.v01.population.*;

import org.matsim.core.population.PopulationUtils;


import java.io.*;




public class AddAttributeActivity {

	public static void main(String[] args) throws IOException {
		// Read the existing population XML file
		String spatial = "/home/sara/data/input_matsim/baseScenario/synpop10/xml/spatial_index.csv";

		BufferedReader bf = new BufferedReader(new FileReader(new File(spatial)));
		bf.readLine();
		Population newPopulation = PopulationUtils.readPopulation("/home/sara/data/input_matsim/baseScenario/synpop10/xml/population.xml.gz");

		String line = null;

		while((line = bf.readLine())!=null){
			String[] part = line.split(",");
			Id<Person> personId = Id.createPersonId(part[1]);
			int actSeq = (int)Double.parseDouble(part[2].replace("\"",""));
			double density_o = Double.parseDouble(part[3]);
			double hhi_o = Double.parseDouble(part[4]);
			double density_d = Double.parseDouble(part[5]);
			double hhi_d = Double.parseDouble(part[6]);
			if(newPopulation.getPersons().get(personId)!=null) {
				Activity act = (Activity) newPopulation.getPersons().get(personId).getSelectedPlan().getPlanElements().get(2 * (actSeq - 1));
				act.getAttributes().putAttribute("density_o", density_o);
				act.getAttributes().putAttribute("hhi_o", hhi_o);
				act.getAttributes().putAttribute("density_d", density_d);
				act.getAttributes().putAttribute("hhi_d", hhi_d);
			}
		}
		new PopulationWriter(newPopulation).write("/home/sara/data/input_matsim/baseScenario/synpop10/xml/population_final.xml.gz");

	}


}
