### ISSUE TITLE
Adding motorcycles

### ISSUE THREAD

**Issue by Nitnelav** [eqasim-org/eqasim-java#170]
Hello !
I am trying to add motorcycles to Eqasim..

I'm almost there :

I generate the vehicle fleet in the pipeline
I get a "motocycleAvailability" in the population
I added Motorcyles classes (Estimator, CostModel, Variable, Predictor, etc.)
I added "motorcyle" in the right places in the config file.
the last thing I'm struggling with is making the motorcycle legs appear in the events file. The motorcycle trips are evaluated in the the DMC replanning part and the routes are in the population file but it looks like the trips don't enter the actual QSim part ... And the issue is that they don't have any "vehicles" attached to it.

at some point I add these line to provide a TripRouter for Motorcycle :
```java
controller.addOverridingModule(new AbstractModule() {
	@Override
	public void install() {
		addRoutingModuleBinding("motorcycle").toProvider(new NetworkRoutingProvider("motorcycle"));
	}
});
```
But I have the feeling it is not enough for the QSim part to kick in...

Do you have any clues ?

**Comment by Nitnelav** [comment]
(It looks like I just forgot to add "motorcycles" to the qsim config "mainModes" but I didn't)
```xml
...
	<module name="qsim" >
		<param name="endTime" value="30:00:00" />
		<param name="filterSnapshots" value="no" />
		<param name="flowCapacityFactor" value="0.1" />
		<param name="insertingWaitingVehiclesBeforeDrivingVehicles" value="true" />
		<param name="isRestrictingSeepage" value="true" />
		<param name="isSeepModeStorageFree" value="false" />
		<param name="linkDynamics" value="FIFO" />
		<param name="linkWidth" value="30.0" />
		<param name="mainMode" value="car, motorcycle" />
		<param name="nodeOffset" value="0.0" />
		<param name="numberOfThreads" value="12" />
		<param name="removeStuckVehicles" value="false" />
		<param name="seepMode" value="motorcycle,bike" />
		<param name="simEndtimeInterpretation" value="null" />
		<param name="simStarttimeInterpretation" value="maxOfStarttimeAndEarliestActivityEnd" />
		<param name="snapshotStyle" value="equiDist" />
		<param name="snapshotperiod" value="00:00:00" />
		<param name="startTime" value="undefined" />
		<param name="storageCapacityFactor" value="0.1" />
		<param name="stuckTime" value="10.0" />
		<param name="timeStepSize" value="00:00:01" />
		<param name="trafficDynamics" value="queue" />
		<param name="useLanes" value="false" />
		<param name="usePersonIdForMissingVehicleId" value="false" />
		<param name="usingFastCapacityUpdate" value="true" />
		<param name="vehicleBehavior" value="teleport" />
		<param name="vehiclesSource" value="fromVehiclesData" />
	</module>
...
```

**Comment by Nitnelav** [comment]
ah I think I firgured it out... the space in `mainModes `is not trimmed ... 😢

**Comment by sebhoerl** [comment]
Nice! I'm wondering if motorcycle should be a separate mode or rather "car" should become "imt" (individual motorized transport) with either a "car" or "motorcycle" vehicle behind depending on the agent? But having it as a separate mode is definitely already nice!

And besides we could manage what I just said as well through the mode availability. We can have agents that have either "car" or "motorbike", and in that sense it makes even sense to have some agents that can choose from both if they actually have both :)

**Comment by Nitnelav** [comment]
Yes I implemented everything as you described it, with a "motorcycleAvailability".

Having separate modes is cool 'cause I am also able to test the SeepageQ QSim option. So far it seems to perform quite well but I still need to make sure everything is fine. 

The last issue is actually attributing the "motorcycleAvailability" to the population. The "DEROU" variable in the census is empty outside of some DOM/TOM departements. so I am using the "TRANS" variable, but it is not satisfactory.
I am going to try some machine learning magic on the HTS to try to guess the parameter HTS data.
As a last resort we can grab the "number_of motorcycles" from the HTS post statistical matching but it seems like the worst option.

PS : the `addOverridingModule` is actually not need with the proper `qsim.mainMode` definition
