### ISSUE TITLE
Problem using RunScenarioCutter to cut the scenario

### ISSUE THREAD

**Issue by syhwawa** [eqasim-org/eqasim-java#189]
Hello, I successfully used the ile_de_france jar file from the eqasim repo to cut a MATSim scenario, following the [documentation](https://github.com/eqasim-org/eqasim-java/blob/develop/docs/cutting.md).

Now, I'm considering if it's feasible to use this tool for scenarios outside of `switzerland` or `ile_de_france`, which could significantly enhance the efficiency of our simulations.

I intend to test the scenario cutter using a small, open-source simulation project named Londinium on GitHub. Here are the [MATSim config](https://github.com/arup-group/londinium/blob/master/matsim/hermes_matsim_config_londinium.xml) and [population](https://github.com/arup-group/londinium/blob/master/data/population/population.xml) files I used for testing.

I'm curious whether the cutter requires specific MATSim configuration settings and plan inputs to be compatible. An error I encountered while cutting the test scenario suggested that each activity in the plans.xml might need an associated facility:

```
2023-10-31T15:34:33,149 ERROR ScenarioValidator:66 Person agent_99 has park activity without facility
2023-10-31T15:34:33,149 ERROR ScenarioValidator:66 Person agent_99 has shop activity without facility
2023-10-31T15:34:33,150 ERROR ScenarioValidator:66 Person agent_99 has home activity without facility
Exception in thread "main" java.lang.IllegalStateException: Found errors while checking population
        at org.eqasim.core.scenario.validation.ScenarioValidator.checkScenario(ScenarioValidator.java:196)
        at org.eqasim.core.scenario.cutter.RunScenarioCutter.main(RunScenarioCutter.java:84)
``` 

Here's an example activity from the test plan.xml:

```
    </attributes>
    <plan selected="yes">
      <activity type="home" x="528634.2579046559" y="176896.66392752415" end_time="07:58:00"/>
      <leg mode="car" trav_time="00:25:00"/>
```
Does it require the addition of a facility to the activity plan, like so?
```
      <activity type="home" facility="home_hh_0" x="528634.2579046559" y="176896.66392752415" end_time="07:58:00"/>
```
---
I also wonder if specific MATSim configuration settings, such as the qsim mobility module, are necessary for compatibility with the cutter.

When I tried to comment out the validating statement in the `core/src/main/java/org/eqasim/core/scenario/validation/ScenarioValidator.java`, I met another error:

```
2024-02-01T17:48:34,359  INFO Injector:94   ==full==> ConstructorBinding{key=Key[type=org.matsim.core.trafficmonitoring.TravelTimeCalculator, annotation=[none]], source=org.matsim.core.trafficmonitoring.TravelTimeCalculatorModule.install(TravelTimeCalculatorModule.java:87), scope=Scopes.SINGLETON}
2024-02-01T17:48:34,359  INFO Injector:96 
2024-02-01T17:48:34,359  INFO Injector:99 === printInjector end ===
2024-02-01T17:48:34,368  INFO ParallelProgress:26 Cutting population ... 0/100 (0.00%)
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInCustomProvider]: IllegalStateException: Cutter does not support teleportedModeFreespeedFactor yet!
  at PopulationCutterModule.provideModeAwareTripProcessor(PopulationCutterModule.java:120)
      \_ installed by: Modules$CombinedModule -> Modules$CombinedModule -> AbstractModule$4 -> Modules$OverrideModule -> AbstractModule$4 -> Modules$OverrideModule -> AbstractModule$4 -> Modules$OverrideModule -> AbstractModule$4 -> Modules$OverrideModule -> PopulationCutterModule
  while locating ModeAwareTripProcessor
  at PlanCutter.<init>(PlanCutter.java:25)
      \_ for 1st parameter
  while locating PlanCutter

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER

1 error
```

It seems like it doesn't like some matsim config setting. 

Could you please advise on any required modifications to the MATSim configuration and plans for successful testing scenario cutting?

Many thanks for your help in advance.

**Comment by sebhoerl** [comment]
In principle, you can use the cutter for any MATSim input data that is formatted in the right way. In the eqasim framework we make sure to follow a couple of clear conventions when we *generate* the MATSim data. For instance, every activity should have coordinates, a link ID, and a facility ID. And the coordinates should coincide with the coordinates of the facility. This way we make sure that everything is coherent when we look things up later in MATSim.

Also, we don't use `teleportedModeFreespeedFactor` for routing in our scenarios, which seems to be the case for you. You may need to extend the code to properly cut these kind of modes, or you may just define them as network modes (`networkModes`) with the respective data encoded in you MATSim network.

Yes, everything is cut to the provided perimeter. Have a look at chapter 4.2 here to see the whole concept:
https://www.research-collection.ethz.ch/handle/20.500.11850/419837

**Comment by syhwawa** [comment]
Thanks for your reply and information.

> In principle, you can use the cutter for any MATSim input data that is formatted in the right way. In the eqasim framework we make sure to follow a couple of clear conventions when we generate the MATSim data. For instance, every activity should have coordinates, a link ID, and a facility ID. And the coordinates should coincide with the coordinates of the facility. This way we make sure that everything is coherent when we look things up later in MATSim.

Do you mean we should make a link IS, coordinates and felicity ID within the created population so the cutter can cut the scenario? Does the cutter accept the empty facility file or if we have way to ingore the facility?

> Also, we don't use teleportedModeFreespeedFactor for routing in our scenarios, which seems to be the case for you. You may need to extend the code to properly cut these kind of modes, or you may just define them as network modes (networkModes) with the respective data encoded in you MATSim network.

I think we may not use the `teleportedModeFreespeedFactor` since I didn't find any setting related the that parameters. Do you think if it will be other module which is not compatible with required matsim config for cutting.

I compared that with ile-de-france matsim config which looks similar.  Here is the module which has `networkModes` that we used:

```
  	<module name="planscalcroute" >
		<!-- Some typical teleportation routing params are set by default, such as for walk and bike.  Setting this switch to "true" will clear them.  Note that this will also clear settings for helper modes such as for non_network_walk -->
		<param name="clearDefaultTeleportedModeParams" value="false" />
		<!-- All the modes for which the router is supposed to generate network routes (like car) -->
		<param name="networkModes" value="car" />
		<!-- strength of the randomness for the utility of money in routing under toll.  Leads to Pareto-optimal route with randomly drawn money-vs-other-attributes tradeoff. Technically the width parameter of a log-normal distribution. 3.0 seems to be a good value.  -->
		<param name="routingRandomness" value="0.0" />
		<parameterset type="teleportedModeParameters" >
			<param name="beelineDistanceFactor" value="1.4" />
			<param name="mode" value="bike" />
			<param name="teleportedModeFreespeedFactor" value="null" />
			<param name="teleportedModeSpeed" value="3.1" />
		</parameterset>
		<parameterset type="teleportedModeParameters" >
			<param name="beelineDistanceFactor" value="1.3" />
			<param name="mode" value="walk" />
			<param name="teleportedModeFreespeedFactor" value="null" />
			<param name="teleportedModeSpeed" value="1.2" />
		</parameterset>
```

Much appreciate if you can take a look or you have any clues that I need to check for my matsim config. Thanks.
