### ISSUE TITLE
Problem executing sao_paulo pipeline after commit c529f21

### ISSUE THREAD

**Issue by MayuriAnn** [eqasim-org/eqasim-java#191]
Hi. I tried using the sao_paulo pipeline a few months ago to generate files and simulation and it worked fine. Last week I tried to run the pipeline again and an exception popped up when executing matsim.simulation.prepare:

`java.lang.RuntimeException: Could not retrieve vehicle id from person: 100266. 
If you are not using config.qsim().getVehicleSource() with 'defaultVehicle' or 'modeVehicleTypesFromVehiclesData' you have to provide a vehicle for each mode for each person. Attach a PersonVehicles instance (containing a map of mode:String -> id:Id<Vehicle>) with key 'vehicles' as person attribute to each person.  VehicleUtils.insertVehicleIdIntoAttributes does this for you.`

The complete log of the java command that is failing can be viewed [here](https://gist.github.com/MayuriAnn/ad3d8e524e1a858a259e98f363cc58f6).

I did some tests and found out that the exception starts after commit “feat: car access/egress (#183) [c529f21]”, before this commit the pipeline completes all steps successfully.

I am new to Java, Matsim, and Eqasim and could not find how to avoid this exception. Do you have any ideas about what needs to be changed or what is missing?

**Comment by sebhoerl** [comment]
Hi, how familiar are you with the Python pipeline? There hasn't been many active updated recently for São Paulo, so the pipeline is a bit behind the code in the Java repository here. To exactly avoid those mismatches, we have recently fixed the commit of the Java code that is used inside the pipeline for the Paris version: 

https://github.com/eqasim-org/ile-de-france/blob/develop/matsim/runtime/eqasim.py#L9

You could replace this step in the pipeline with the Paris version (with some adaptations) to fix the commit to the last one that works properly. Would be great if you could send a PR for that. 

The next step would then be to check why the error happens in the newer version. Probably one needs to define a vehicle attribute per person, and it seems like we do that for the Paris case recently. But I would need to dig deeper to see where this happens exactly.

**Comment by MayuriAnn** [comment]
From the [link](https://github.com/eqasim-org/ile-de-france/blob/develop/matsim/runtime/eqasim.py#L9), the default commit being used for Paris 

`DEFAULT_EQASIM_COMMIT = "7cbe85b"`

was working for sao_paulo as well. I tested 7cbe85b, c2bc9a4, bf6de83, b1331d7, and 71239c0, the last one without the exception. The problem starts after c529f21. Is the Paris pipeline working after this commit?

**Comment by sebhoerl** [comment]
Good point. I'm pretty sure I ran it, but I will verify.

**Comment by sebhoerl** [comment]
So I verified and you're right. The code only worked with a specific internal version of the pipeline. I just added a PR that fixes the routing stage. Please try with [a8a73b5](https://github.com/eqasim-org/eqasim-java/commit/a8a73b53dbfc085e6eabddcd8ba43fd72013b063). Thanks for pointing it out, and let me know if it works :)

**Comment by MayuriAnn** [comment]
The vehicle issue is fixed and matsim.simulation.prepare now finishes the processing. However, now when executing stage matsim.simulation.run, a new exception arose on iteration 1 (iteration 0 ends as expected):

`java.lang.IllegalStateException: We do not support multi-stage taxi trips yet.
        at org.eqasim.sao_paulo.mode_choice.utilities.predictors.SaoPauloTaxiPredictor.predict(SaoPauloTaxiPredictor.java:28) ~[sao_paulo-1.3.1.jar:?]`

 Check [here](https://gist.github.com/MayuriAnn/22aeef9523b796c6f506d486d602c137) for the relevant part of the log.

Any ideas on how to prevent this "multi-stage taxi trips"?

**Comment by sebhoerl** [comment]
Hi, the problem is that your taxi trips are now "walk to link" - "take taxi" - "walk to destination", but before the agent was just assumed to be located at the origin and destination links for the road travel. This is something that has been updated for the car:
https://github.com/eqasim-org/eqasim-java/blob/a8a73b53dbfc085e6eabddcd8ba43fd72013b063/core/src/main/java/org/eqasim/core/simulation/mode_choice/utilities/predictors/CarPredictor.java#L36-L45

But since we don't model taxi individually in Paris, this also slipped the validation process. You may have a look at the taxi predictor for SP and adjust it like we did for the car case above:
https://github.com/eqasim-org/eqasim-java/blob/a8a73b53dbfc085e6eabddcd8ba43fd72013b063/sao_paulo/src/main/java/org/eqasim/sao_paulo/mode_choice/utilities/predictors/SaoPauloTaxiPredictor.java#L27-L39

Let me know if this is something you could look into. Otherwise, maybe @balacmi would be willing to help as well? :)

**Comment by MayuriAnn** [comment]
I managed to update [SaoPauloTaxiPredictor.java](https://github.com/eqasim-org/eqasim-java/blob/a8a73b53dbfc085e6eabddcd8ba43fd72013b063/sao_paulo/src/main/java/org/eqasim/sao_paulo/mode_choice/utilities/predictors/SaoPauloTaxiPredictor.java#L27-L39) following the code of [CarPredictor.java](https://github.com/eqasim-org/eqasim-java/blob/a8a73b53dbfc085e6eabddcd8ba43fd72013b063/core/src/main/java/org/eqasim/core/simulation/mode_choice/utilities/predictors/CarPredictor.java#L36-L45). Then I run complete São Paulo pipeline and it did finish all steps.

I did a PR with the updated code. Thanks with the help!
