### ISSUE TITLE
Handling of vehicles

### ISSUE THREAD

**Issue by sebhoerl** [eqasim-org/eqasim-java#225]
There are several incompatibilities depending on which steps we run in the pipeline and cutting etc. regarding whether there are errors regarding vehicles. I propose to include them by default now, even if it is just standard vehicle placeholders.

- [ ] Phase out `RunPopulationRouting.insertVehicles` and `RunPopulationRouting.clearVehicles`
- [ ] Add vehicles by default in the pipeline

**Comment by Nitnelav** [comment]
+1, the vehicleType would be standard by default or some HBEFA-compatible type if enabled.
Also the pipeline should put them directly in the XML to make it clear.

**Comment by sebhoerl** [comment]
Yes, thanks.
