### ISSUE TITLE
Simulate public transport vehicles

### ISSUE THREAD

**Issue by sebhoerl** [eqasim-org/eqasim-java#45]
We need to check whether we can run eqasim with simulated public transport (from standard MATSim or SwissRailRaptor). A couple of points to check:

- Check whether eqasim scenarios run with standard PT / SwissRail PT
- Problems are expected for the utility estimators, as we usually do not know waiting time. Two options: for another project we have implemented tools to recover planned waiting times (and the code is included in the current `develop` branch of DMC); or we can switch to a newer weekly SNAPSHOT of MATSim, as I have implemented into the new standard routes of MATSim there.
- Check that cutting works (hint: it doesn't, because there are problems with "Umlauf")
- Compare our simulation-free PT approach with the simulation-fee approach of SwissRail. In case runtimes (and results) are similar, we can drop the specific implementation here!

**Comment by balacmi** [comment]
I am not sure that we need to estimate wait times for pt. I am thinking that this would be an overkill, except for the situations where the headway might be 30min, but in the areas where the headway is this large I would also not expect any traffic congestion. So I would stick with the estimates based on the schedule.

**Comment by sebhoerl** [comment]
This was a misunderstanding then. The standard MATSim PT router (and SwissRailRaptor so far) did not return the waiting time. For an interchange the router would create a `pt interaction` activity with zero duration and afterwards there would be a leg. But the travel time of this leg includes waiting for the vehicle and waiting at the stop. So from that information it was not pobvious how long the agent is waiting at the stop before the vehicle arrives. (In the new weekly SNAPSHOT this is included now). So before, we needed to look up the line and route of the leg, together with the stop facility and the departure time of the leg to figure out when is the next time a vehicle from that line and route is supposed to stop there:

https://github.com/matsim-eth/discrete-mode-choice/blob/develop/src/main/java/ch/ethz/matsim/discrete_mode_choice/components/utils/ScheduleWaitingTimeEstimator.java
