### ISSUE TITLE
Remove Location Assignment

### ISSUE THREAD

**Issue by sebhoerl** [eqasim-org/eqasim-java#70]
Location assignment is now a part of the pipeline (Python) code. Eventually, we should remove this component from here as the implementation there is more stable and easier to maintain.

**Comment by sebhoerl** [comment]
@ctchervenkov @balacmi Is there any pipeline which still uses Java location assignment code, or has everything been ported to the Python version by now?

**Comment by balacmi** [comment]
California, and Sao Paulo are ported to the Python version. @ctchervenkov should know about the Swiss

**Comment by ctchervenkov** [comment]
I also ported Switzerland to the Python version.

Chris

-----
*Christopher Tchervenkov*

Tel: +41 76 510 39 33
Mail: ***@***.***
Skype: ctchervenkov
