### ISSUE TITLE
Problem in generate trips.csv  of output plan

### ISSUE THREAD

**Issue by gharaviSara** [eqasim-org/eqasim-java#82]
Hi @sebhoerl  and @balacmi  
I found an issue in eqasim output CSV , as you see below the input_plan.xml and output_plan.xml for certain number of agents (5000 out of 7600) in the origin and destination coordinates did not change and it always returns zero euclidean  distance. I assume the code that parse output plans and change it to trips.csv format has a problem .

it would be nice if you can fix it.
![image](https://user-images.githubusercontent.com/61546453/101927919-4c5a6f00-3bd5-11eb-8892-4d7aa542666a.png)

**Comment by gharaviSara** [comment]
/home/sara/Pictures/Screenshot from 2020-12-11 17-22-41.png
/home/sara/Pictures/Screenshot from 2020-12-11 17-21-53.png

**Comment by sebhoerl** [comment]
Hi Sara, can you upload a reduced population file (like 2-3 persons) for which the problem happens? Then we could make a unit test for that.

**Comment by sebhoerl** [comment]
One more question: Are we talking about the `trips.csv` that is generated automatically by the simulation, the one that is converted from an events file, or really specifically the one that is generated from a population file?

**Comment by gharaviSara** [comment]
Dear sebastian.
Its exactly the trips.csv file automatically generated from simulation part
.that it's only the parsed format of output_plans.xml file .I can parse it
separately in my analysis notebook but it is an issue should be considered
for next user.

Many thanks.

**Comment by sebhoerl** [comment]
Sorry, I don't understand. The file you generate automatically in the simulation is based on events. But you mention, that you generate the file from the plans. Which one causes the problem?

**Comment by sebhoerl** [comment]
Can you (person 100068) as a text file so I can test?

**Comment by sebhoerl** [comment]
I just noticed something else: The value `248502` that you have in the trips.csv does never show up in your screenshots of the plans. Are you sure you are comparing the right files? 

Another thought: Can it be that you have duplicate person IDs in your input plans?

I was checking a bit the code and cannot see any obvious problems, both for the plans and events analysis. So without any example input/output files where the problem occurs, it will be difficult to track it down. Hence my asking for the files and looking into other potential causes. :)

**Comment by gharaviSara** [comment]
Hi Sebastian,

Here you can find the automatically generated output in my simulation and
30th iteration the locations are the same for many agents. I did it before
in jupyter notebook and I sent it in your slack , slack when I  then it
gets the first locations in first row and copy it for all agents ,please
check your slack .
Cheers,

 30.trips.csv.gz
<https://drive.google.com/file/d/1RhnzuA9To4Lm9qqT_sBYMovRiHzAVWkt/view?usp=drive_web>

 output_plans.xml.gz
<https://drive.google.com/file/d/1x-VGMH4k7Lq4GjTgQkScm18YnnDQdyOS/view?usp=drive_web>

 output_trips.csv.gz
<https://drive.google.com/file/d/1x352YxI6M0vuAIGe3OxNhvfIomAxB-0G/view?usp=drive_web>

 output_events.xml.gz
<https://drive.google.com/file/d/1Ymq-hih2b56ZbuLhCcebHpw01VCwbXx4/view?usp=drive_web>

Sara

**Comment by sebhoerl** [comment]
Hi Sara,

I was looking into your `output_plans.xml.gz` and then I generated the `trips.csv` with the `RunTripAnalysis` script. This is what you are trying to do as far as I understand? For me the analysis output looks normal:

![Screenshot from 2021-01-01 15-34-40](https://user-images.githubusercontent.com/647500/103440583-23af1d80-4c47-11eb-80a9-03c5af1bbf01.png)

Can you describe again what exactly you are doing? Again my question: Do you want to generate the `trips.csv` from the plans or from the events? Or are we talking about the file that is generated automatically in eqasim (which is based on events). In that case I would also need the network to check running `RunTripAnalysis` based on events.

**Comment by gharaviSara** [comment]
Hi Sebastian,

First I hope you a happy and wonderful new year, as you see in the
screenshot I did the same command for the 10.trips.csv in my last iteration
folder and the locations are copy and duplicated,
-I don't know that this 10.trips.csv is out of events file or plans, it
normally automatically appear after the run,
maybe in a config file, I made a mistake,

I let you have full access to my output and input folder
Cheers,
Sara

**Comment by sebhoerl** [comment]
Hi Sara, there is no problem with the trips analysis. Have a look at your `output_events.xml` for agent `206588`:

![Screenshot from 2021-01-04 12-11-34](https://user-images.githubusercontent.com/647500/103529464-061bc700-4e86-11eb-9b38-2e0c4d943570.png)

The agent leaves at link `2844` and also arrives at link `2844` for the first trip, and the opposite for the trip back. So the agent doesn't actually move in the simulation, so the analysis is correct.

Look at the plan for agent `206588` in `output_plans.xml.gz`. The information that is important for the car simulation is the link ID. Both activities have link `2844` and they have the facilities `home98432` and `408864`.

![Screenshot from 2021-01-04 12-13-35](https://user-images.githubusercontent.com/647500/103529785-91955800-4e86-11eb-8dc4-c258218e9420.png)

Looking in your `output_faciltiies.xml.gz` I can see that facility `home98432` is at link `2844` and also the other facility. So in that sense everything is consistent. But note that facilities are *attached* to a link and MATSim usually makes use of the link information, not the actual coordinates. So what is mandatory is to which link a facility is attached. In your case it seems that you attach facilities to links that are quite far away.
