### ISSUE TITLE
TransitEngine cannot be removed as it is not registered 

### ISSUE THREAD

**Issue by balacmi** [eqasim-org/eqasim-java#90]
In order to remove transit vehicles from mobsim, one now can set usingTransitInMobsim to false in transit module in the config. However, the following will not work anymore:

https://github.com/eqasim-org/eqasim-java/blob/8c4481fc02ab6e95fc4ecb12850776298b21c3bf/core/src/main/java/org/eqasim/core/components/transit/EqasimTransitQSimModule.java#L35

This needs to be updated to reflect MATSim v12.0 workings.

**Comment by ctchervenkov** [comment]
A simple solution is to first check if this component is registered before trying to remove it.
